### ISSUE TITLE
Dockware behind a reverse Proxy?

### ISSUE THREAD

**Issue by Sim0nW0lf** [dockware/dockware#103]
Hi, I am wondering if it's possible to host Dockware behind a reverse proxy like Traefik?

I have tried this docker-compose.yml:
```
version: '3'

services:
  shop:
    container_name: shop
    image: dockware/dev:latest
    ports:
      - "222:22"     # ssh
      - "800:80"     # apache2
      - "4430:443"   # apache2 https
      - "8888:8888" # watch admin
      - "9998:9998" # watch storefront proxy
      - "9999:9999" # watch storefront
      - "3306:3306" # mysql port
    networks:
      - proxy
    environment:
      - XDEBUG_ENABLED=0

networks:
  proxy:
    external: true
```
with this traefik dynamic configuration:
```
  # Define a connection between requests and services
  # https://doc.traefik.io/traefik/routing/overview/
  routers:
    to-https-shopware:
      entryPoints:
      - https
      rule: "Host(`shopware.secureserver.de`)"
      # If the rule matches, applies the middleware
      middlewares:
      - secHeaders
      # This is for https
      tls:
        options: default
        certResolver: "http" # cert resolver is defined in traefik.yml
      # If the rule matches, forward to the shopware service (declared below)
      service: shopware

    to-shopware:
      entryPoints:
      - http
      rule: "Host(`shopware.secureserver.de`)"
      # If the rule matches, applies the middleware
      middlewares:
      - secHeaders
      # If the rule matches, forward to the shopware service (declared below)
      service: shopware

  services:
    # Define how to reach an existing service on our infrastructure
    shopware:
      loadBalancer:
        servers:
        - url: "http://123456789:800"
```

But when I visit https://shopware.secureserver.de/admin I only get a blank page. Similarly when I try to redirect to a storefront it only shows Text, not css styling like this:
![grafik](https://user-images.githubusercontent.com/31454341/155171405-4733d5f3-d6c2-4fbf-8430-f5a5858b1211.png)
