### ISSUE TITLE
adding volumes to docker-compose causes mysql to fail starting

### ISSUE THREAD

**Issue by rosariop** [dockware/dockware#104]
**Describe the bug**
When adding volumes to the docker-compose file provided on the dockware/play dockerhub page the container does not start and throw following error:
```
shopware    | DOCKWARE: starting MySQL....
shopware    |  * Starting MySQL database server mysqld
shopware    |    ...fail!
shopware exited with code 1
```
**To Reproduce**
copy/paste following docker-compose.yml
```yml
shopware:
    image: dockware/play:latest
    container_name: shopware
    volumes:
        - ./data:/var/lib/mysql
        - ./web:/var/www/html
    ports:
        - "80:80"
        - "443:443"
        - "22:22"
    environment:
        - PHP_VERSION=7.4

```
run `docker-compose up`

**Expected behavior**
the container starts and persists the two directories.

**Desktop (please complete the following information):**
 - OS: Fedora Linux 35 (Workstation Edition)
 - Docker Version: 20.10.12, build e91ed57
 - docker-compose version: 1.29.2, build 5becea4c

full stacktrace:
```
Starting shopware ... done
Attaching to shopware
shopware    | 
shopware    |  _____   ____   _____ _  ____          __     _____  ______ 
shopware    | |  __ \ / __ \ / ____| |/ /\ \        / /\   |  __ \|  ____|
shopware    | | |  | | |  | | |    | ' /  \ \  /\  / /  \  | |__) | |__   
shopware    | | |  | | |  | | |    |  <    \ \/  \/ / /\ \ |  _  /|  __|  
shopware    | | |__| | |__| | |____| . \    \  /\  / ____ \| | \ \| |____ 
shopware    | |_____/ \____/ \_____|_|\_\    \/  \/_/    \_\_|  \_\______|
shopware    | 
shopware    | 68 69 20 64 65 76 65 6C 6F 70 65 72 2C 20 6E 69 63 65 20 74 6F 20 6D 65 65 74 20 79 6F 75
shopware    | 6c 6f 6f 6b 69 6e 67 20 66 6f 72 20 61 20 6a 6f 62 3f 20 77 72 69 74 65 20 75 73 20 61 74 20 6a 6f 62 73 40 64 61 73 69 73 74 77 65 62 2e 64 65
shopware    | 
shopware    | *******************************************************
shopware    | ** DOCKWARE IMAGE: play
shopware    | ** Tag: latest
shopware    | ** Version: 1.4.3
shopware    | ** Built: Mon Feb 14 15:23:10 UTC 2022
shopware    | ** Copyright 2021 dasistweb GmbH
shopware    | *******************************************************
shopware    | 
shopware    | launching dockware...please wait...
shopware    | 
shopware    | DOCKWARE: setting timezone to Europe/Berlin...
shopware    | 
shopware    | Current default time zone: 'Europe/Berlin'
shopware    | Local time is now:      Mon Feb 28 20:16:46 CET 2022.
shopware    | Universal Time is now:  Mon Feb 28 19:16:46 UTC 2022.
shopware    | 
shopware    | -----------------------------------------------------------
shopware    | DOCKWARE: starting MySQL....
shopware    |  * Starting MySQL database server mysqld
shopware    |    ...fail!
shopware exited with code 1
```

**Comment by thomasmax-97** [comment]
same issue here

**Comment by Vandaahl** [comment]
I am running into this as well with the 'essentials' image. However, you can [persist your database](https://docs.dockware.io/tips-and-tricks/persisting-data) like this:

```
version: "3"

services:
  dockware:
    image: dockware/essentials:latest
    container_name: dockware
    ports:
      - "8433:80"
      - "2288:22"
      # Admin Watcher Port
      - "8800:8888"
      # Storefront Watcher Port
      - "9900:9999"
    environment:
      - PHP_VERSION=8.1
      - XDEBUG_ENABLED=0
    volumes:
      - "db_volume:/var/lib/mysql" # Persist database
      - ./www:/var/www/html

# Persist database
volumes:
  db_volume:
    driver: local
```
