### ISSUE TITLE
Under WSL2 "failed to register layer: max depth exceeded"

### ISSUE THREAD

**Issue by PrinzMonty** [dockware/dockware#108]
**Describe the bug**
When I start Dockware under WSL2 with docker-compose I get an error. This error only comes when i use the "dev" image.

**To Reproduce**
docker-compose up
Error: failed to register layer: max depth exceeded

**Additional context**

Compose File:

```yml
version: "3.8"

services:

  shopware:
    image: dockware/dev:5.7.7
    container_name: shopware
    volumes:
      - ./plugins:/var/www/html/custom/plugins
    ports:
      - "80:80"
      - "3306:3306"
      - "22:22"
      - "8888:8888"
      - "9999:9999"
    networks:
      - web
    environment:
      - PHP_VERSION=7.4
      - SSH_USER=userABC
      - SSH_PWD=supersecret
      - XDEBUG_ENABLED=1

networks:
  web:
    external: false
```
