### ISSUE TITLE
Error while running watch-storefront script

### ISSUE THREAD

**Issue by hagmann** [dockware/dockware#11]
While running watch-storefront, the following error occurred:
![image](https://user-images.githubusercontent.com/11349379/93527176-c366cb00-f938-11ea-9c2f-a9607a46c647.png)

The compilation was still successful, but the JS files are not being loaded using port 9999:
![image](https://user-images.githubusercontent.com/11349379/93527128-b2b65500-f938-11ea-93ce-55c212baf74b.png)

This may lead to this error:
![image](https://user-images.githubusercontent.com/11349379/93527020-93b7c300-f938-11ea-9029-b2d9ded4198e.png)

The sources are available as expected on localhost:9999.

System details:
Windows 10 Pro
Docker Toolbox

**Comment by martinweinmayr** [comment]
@hagmann which dockware image are you running?

**Comment by hagmann** [comment]
@martinweinmayr 

Dockerfile:

```
version: "3"

services:

  shopware:
    image: dockware/dev:latest
    container_name: badminton-onlineshop
    ports:
      - "80:80"
      - "3306:3306"
      - "222:22"
      - "8888:8888"
      - "9999:9999"
    networks:
      - web
    environment:
      - SW_CURRENCY=CHF
      - XDEBUG_ENABLED=1
      - XDEBUG_REMOTE_HOST=192.168.99.101

networks:
  web:
    external: false
```

I started the watcher using 
```
cd /var/www
make watch-storefront
```
