### ISSUE TITLE
docker cp copies production rather then development

### ISSUE THREAD

**Issue by Richard2012** [dockware/dockware#114]
I have **dockware/dev** image in my Docker Desktop
After executing
`docker cp shopware:/var/www/html/. ./src`
production environment (and not development) is created in the ./src directory. It includes /vendor subdirectory

This is my docker-compose.yml:
```
version: "3"

services:

  shopware:
    image: dockware/dev:6.4.10.1
    container_name: shopware
    ports:
      - "80:80"
      - "3306:3306"
      - "22:22"
      - "8888:8888"
      - "9999:9999"
    volumes:
      - "db_volume:/var/lib/mysql"
      - "shop_volume:/var/www/html"
    networks:
      - web
    environment:
      - XDEBUG_ENABLED=0
      - PHP_VERSION=7.4.8

volumes:
  db_volume:
    driver: local
  shop_volume:
    driver: local

networks:
  web:
    external: false

```

And this is the fist line of the composer.json in the created code:
`    "name": "shopware/production",
`
