### ISSUE TITLE
Mount /dev/urandom on Linux hosts

### ISSUE THREAD

**Issue by seybsen** [dockware/dockware#115]
I noticed that when using dockware with docker-compose on linux (ubuntu) and creating a lot of UUIDs via `\Shopware\Core\Framework\Uuid\Uuid::randomHex()` sometimes duplicates are generated.

Mounting `/dev/urandom` to the container helps to have enough entropy to generate unique UUIDs again:

docker-compose.yml:

```
services:
  shopware:
    image: dockware/dev:latest
    container_name: shopware
    ports:
      - "80:80"
      - "3306:3306"
      - "22:22"
      - "8888:8888"
      - "9999:9999"
    volumes:
      - "db_volume:/var/lib/mysql"
      - "shop_volume:/var/www/html"
      - "/dev/urandom:/dev/urandom" # bind /dev/urandom
```
