### ISSUE TITLE
watch-storefront: CORS issue on XHR requests from http://localhost:9998 to http://localhost

### ISSUE THREAD

**Issue by seybsen** [dockware/dockware#121]
On a product detail page with default theme I get following error in browser console when trying to switch the variant:

> Access to XMLHttpRequest at 'http://localhost/detail/79d1c4005c484dd1bbb19e0a2821ecd7/switch?options=%7B%227b7fea7f24ca4e1d9b05d0c4ece3e3de%22%3A%22cafe41d4f2814edc842c41f031335e66%22%7D&switched=7b7fea7f24ca4e1d9b05d0c4ece3e3de' from origin 'http://localhost:9998' has been blocked by CORS policy: Request header field x-requested-with is not allowed by Access-Control-Allow-Headers in preflight response.

I'm running dockware/dev:latest (=6.4.11.1) and started the watch-storefront via the makefile like explained here:
https://docs.dockware.io/development/watchers#storefront-watcher

```
docker-compose exec -w /var/www shopware make watch-storefront
```
I verified the `/var/www/html/.htaccess.watch` got created.

Do I need to set any headers manually?

**Comment by seybsen** [comment]
Hey,

I tried plain http and left the storefront URL at its default(?) value `http://localhost`. The webpack proxy was listening on `http://localhost:9998/`.

**Comment by seybsen** [comment]
Reproduction example:

docker-compose.yml
```
version: "3"

services:
  shopware:
    # use either tag "latest" or any other version like "6.1.5", ...
    image: dockware/dev:latest
    container_name: shopware
    ports:
      - "80:80"
      - "3306:3306"
      - "22:22"
      - "8888:8888"
      - "9999:9999"
      - "9998:9998"
    volumes:
      - "db_volume:/var/lib/mysql"
      - "shop_volume:/var/www/html"
      - "/dev/urandom:/dev/urandom"
      - "/dev/urandom:/dev/random"
    networks:
      - web
    environment:
      # default = 0, recommended to be OFF for frontend devs
      - XDEBUG_ENABLED=1
      # default = latest PHP, optional = specific version
      - PHP_VERSION=8.0

volumes:
  db_volume:
    driver: local
  shop_volume:
    driver: local

networks:
  web:
    external: false
```

start container and watch-storefront:

```bash
docker-compose up -d
docker-compose exec -w /var/www shopware make watch-storefront
```

visit http://localhost:9998/Variant-product/SWDEMO10005.5 and switch from size M to XL
