### ISSUE TITLE
Dockware in kubernetes with attached volumes fails at startup

### ISSUE THREAD

**Issue by Stones91** [dockware/dockware#137]
I'm trying to deploy shopware for development in kubernetes (k3s). Without any volumes attached, dockware works without any problems. After attacking volumes for the shopware and mysql-data, the container fails to start up at the "starting MYSQL" step. My current yaml file looks like this: 

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dockware-statefulset
  namespace: dockware
  labels:
    app: dockware
spec:
  serviceName: dockware-service
  replicas: 1
  selector:
    matchLabels:
      app: dockware
  template:
    metadata:
      labels:
        app: dockware
    spec:
      containers:
        - name: dockware
          image: dockware/dev:latest
          resources: {}
          ports:
            - containerPort: 80
              name: shop
            - containerPort: 22
              name: ssh
            - containerPort: 8888
              name: ka1
            - containerPort: 9999
              name: ka2
          volumeMounts:
            - name: db-volume
              mountPath: /var/lib/mysql
            - name: shop-volume
              mountPath: /var/www/html
      volumes:
        - name: db-volume
          persistentVolumeClaim:
            claimName: db-pvc
        - name: shop-volume
          persistentVolumeClaim:
            claimName: shop-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: dockware
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shop-pvc
  namespace: dockware
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
kind: Service
apiVersion: v1
metadata:
  name: dockware-service
  namespace: dockware
spec:
  type: ClusterIP
  selector:
    app: dockware
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
    - name: ka1
      protocol: TCP
      port: 8888
      targetPort: 8888
    - name: ka2
      protocol: TCP
      port: 9999
      targetPort: 9999
```

Attaching the volumes results in the mysql failing at startup.

![Screenshot 2022-09-19 at 14 58 02](https://user-images.githubusercontent.com/18261659/191025837-02867107-f6d4-483c-84b2-bb40593e670b.png)

Any suggestions why this keeps happening?
