### ISSUE TITLE
watch-storefront causes Empty Response

### ISSUE THREAD

**Issue by mapodev** [dockware/dockware#141]
Me and my Programming Partner try to setup dockware for our client. Whenever we start watch-storefront and try to call localhost:9998 or 0.0.0.0:9998 after a proxy of docker with a url like website.local, we get an Empty Response Error in the Webbrowser.

1. Start Container
2. Call `make watch-storefront`
3. Wait until Watcher starts after it compiled the code
4. Call Web Browser on website.local:9998
5. Receiving Empty Response Code

I am awaiting a response of my website with hot reload module.

 - OS: Error appears in MacOS and Windows
 - BraveBrowser and Chrome

**Comment by martinweinmayr** [comment]
hi @mapodev which image do you use?

**Comment by mapodev** [comment]
```
version: "3"
 
services:
 
    shopware:
        image: dockware/dev:6.4.15.1
        container_name: federiko
        ports:
            - "15500:80"   # apache2
            - "15510:3306" # mysql
            - "15522:22"   # ssh
            - "15588:8888" # watch admin
            - "15599:9999" # watch storefront
            - "15598:9998" # watch storefront
            - "15525:1025" # mailcatcher
        networks:
            - web
        environment:
            # change to your needs
            DEBUG_REMOTE_HOST: 192.168.2.15
            PHP_IDE_CONFIG: serverName=tesa-d2c-shop.defender.plan-a.de
            # default = 0, recommended to be OFF for frontend devs
            XDEBUG_ENABLED: 1
            # default = latest PHP, optional = specific version
            PHP_VERSION: 7.4
        volumes:
            - "db_volume:/var/lib/mysql"
            - "shop_volume:/var/www/html"
 
volumes:
    db_volume:
        driver: local
    shop_volume:
        driver: local
 
networks:
    web:
        external: false
```
