### ISSUE TITLE
Bind mount not working with Ubuntu 22.04 in WSL2 (Windows 11)

### ISSUE THREAD

**Issue by Myrmod** [dockware/dockware#146]
**Describe the bug**
When starting the following `docker-compose.yml`. The mounted volume is beign created, but it's empty. Inspecting the container, shows me that things exist in there.

**To Reproduce**
Using the following `docker-compose.yml` use `docker-compose up`
```yml
# docker-compose.yml
version: '3'

services:
  shop:
    image: dockware/dev:latest
    ports:
      - ${SSH_PORT:-22}:22     # ssh
      - ${APACHE_HTTP_PORT:-80}:80     # apache2
      - ${APACHE_HTTPS_PORT:-443}:443   # apache2 https
      - ${ADMIN_PORT:-8888}:8888 # watch admin
      - ${STOREFRONT_PROXY_PORT:-9998}:9998 # watch storefront proxy
      - ${STOREFRONT_PORT:-9999}:9999 # watch storefront
      - ${MYSQL_PORT:-3306}:3306 # mysql port
    volumes:
     - ./src:/var/www/html/custom
    networks:
      - web
    environment:
      - XDEBUG_ENABLED=${XDEBUG_ENABLED:-0}

## ***********************************************************************
##  NETWORKS
## ***********************************************************************
networks:
  web:
    external: false
```

**Expected behavior**
Expect the custom directory to be mounted inside the src directory

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 in WSL2 (Windows 11)

**Additional context**
Since mounting works with other containers with the same usage, I assume the problem might lie withing the image.
