### ISSUE TITLE
watch-storefront takes about 10 minutes

### ISSUE THREAD

**Issue by FelixHeber** [dockware/dockware#157]
Hi to everybody,
i am currently migrating a shopware 5 shop to shopware 6. I started the migration without dockware, so far so good. I then switched to using dockware because i am used to ddev in other projects and everything worked as expected. I used the same database and added my theme (I did a subtheme of the atmos theme by zenit design). Then i tried to use the hot reloader (make watch-storefront) to edit the theme. I happened to have the same error as described in https://github.com/dockware/dockware/issues/56, so i ran build-storefront before. Nothing changed, and there are also two more problems:

- The theme compilation takes 611 Seconds. This cannot be normal?
- http://localhost:9998 only says "localhost refused to connect"
- Saving the theme settings also takes ages - or is this a theme problem?

I am using a Lenovo P14s Workstation with Ubuntu 20.04.5, Dockware is using the dev Profile, Shopware 6.4.18.0, no problems at all in other (also heavier) Projects.

Here's my docker-compose.yml:
```
version: "3"

services:

  shopware:
    # use either tag "latest" or any other version like "6.1.5", ...
    image: dockware/dev:latest
    container_name: shopware
    ports:
      - "80:80"
      - "3306:3306"
      - "22:22"
      - "8888:8888"
      - "9999:9999"
      - "9999:9998"
    volumes:
      - "db_volume:/var/lib/mysql"
      - "./src:/var/www/html/"
    networks:
      - web
    environment:
      # default = 0, recommended to be OFF for frontend devs
      - XDEBUG_ENABLED=0
      # default = latest PHP, optional = specific version
      - PHP_VERSION=7.4

volumes:
  db_volume:
    driver: local
  shop_volume:
    driver: local

networks:
  web:
    external: false
```

thanks for helping out!
