### ISSUE TITLE
Adjust the group id and user id to the host system user

### ISSUE THREAD

**Issue by dg-arboro** [dockware/dockware#163]
Hello,

I'm having a problem getting Dockware to run properly on Windows 11 using WSL2.
When trying to execute `bin/console theme:compile`, the following error is thrown:

```
chmod(): operation not permitted
```

This might have to do with the binds I set up:

```
version: '3.9'

services:
  shop:
    # extend base file in order to properly mount volumes on startup
    extends:
      file: docker-compose-base.yml
      service: shop

    volumes:
      # Mount "mysql" directory to persist changes
      - mysql:/var/lib/mysql

      # Mount ".npm" directory to container to prevent npm from nagging us
      - type: bind
        source: ${PROJECT_DIRECTORY}/.npm
        target: "/var/www/.npm"

      # Mount ".npm" directory to container to prevent npm from nagging us
      - type: bind
        source: ${PROJECT_DIRECTORY}/.npm
        target: "/var/www/.cache"

      # Mount ".npm" directory to container to prevent npm from nagging us
      - type: bind
        source: ${PROJECT_DIRECTORY}/.npm
        target: "/var/www/.config"

      # Mount ".env" file to container to be able to sync environment variables
      - type: bind
        source: ${PROJECT_DIRECTORY}/.env
        target: "/var/www/html/.env"

      # Mount "composer.json" file to container to be able to sync composer changes and required plugins
      - type: bind
        source: ${PROJECT_DIRECTORY}/composer.json
        target: "/var/www/html/composer.json"

      # mount "packages" directory to container to be able to sync package changes
      - type: bind
        source: ${PROJECT_DIRECTORY}/config/packages
        target: "/var/www/html/config/packages"

      # Mount "custom" directory to container to be able to sync plugin changes
      - type: bind
        source: ${PROJECT_DIRECTORY}/custom
        target: "/var/www/html/custom"

      # mount "bundles" directory to container to be able to sync bundle changes
      - type: bind
        source: ${PROJECT_DIRECTORY}/public/bundles
        target: "/var/www/html/public/bundles"

      # mount "media" directory to container to be able to sync media changes
      - type: bind
        source: ${PROJECT_DIRECTORY}/public/media
        target: "/var/www/html/public/media"

      # mount "theme" directory to container to persist themes
      - type: bind
        source: ${PROJECT_DIRECTORY}/public/theme
        target: "/var/www/html/public/theme"

      # mount "thumbnail" directory to container to be able to sync media changes
      - type: bind
        source: ${PROJECT_DIRECTORY}/public/thumbnail
        target: "/var/www/html/public/thumbnail"

      # mount "Resources" directory to container to be able to sync changes to the Storefront theme
      - type: bind
        source: ${PROJECT_DIRECTORY}/vendor/shopware/storefront/Resources
        target: "/var/www/html/vendor/shopware/storefront/Resources"

        # mount "log" directory to container to be able to read log files written by Shopware
      - type: bind
        source: ${PROJECT_DIRECTORY}/var/log
        target: "/var/www/html/var/log"

        # mount "files" directory to container to be able to sync theme config and other files
      - type: bind
        source: ${PROJECT_DIRECTORY}/files
        target: "/var/www/html/files"

      # required to persist current status of selected features (build-storefront/watch-storefront)
      - type: bind
        source: ${PROJECT_DIRECTORY}/var/config_js_features.json
        target: "/var/www/html/var/config_js_features.json"

      # required to persist current status of plugins (build-storefront/watch-storefront)
      - type: bind
        source: ${PROJECT_DIRECTORY}/var/plugins.json
        target: "/var/www/html/var/plugins.json"

      # required to persist paths to currently used theme files (build-storefront/watch-storefront)
      - type: bind
        source: ${PROJECT_DIRECTORY}/var/theme-files.json
        target: "/var/www/html/var/theme-files.json"

      # required to persist theme variables (build-storefront/watch-storefront)
      - type: bind
        source: ${PROJECT_DIRECTORY}/var/theme-variables.scss
        target: "/var/www/html/var/theme-variables.scss"

      # required to persist composer cache
      - type: bind
        source: ${PROJECT_DIRECTORY}/var/cache/composer
        target: "/var/www/html/var/cache/composer"

    ports:
      - "80:80" # HTTP
      - "22:22" # SSH
      - "8888:8888" # Admin watcher Port
      - "9998:9998" # Storefront watcher Port
      - "9999:9999" # Storefront watcher Port
    environment:
      INIT_STATE: "main"

# create volume to make database changes persistent
volumes:
  mysql:
```

I'm passing the `$PROJECT_DIRECTORY` environment variable via a script that I use to start the project with.

I think this feature request could fix my exact problem: https://github.com/dockware/dockware/issues/61
Unfortunately, I don't see it implemented in the image, yet.

I'm not sure if this would break anything, but just to be sure, maybe it would be possible to make this change only for Windows and Linux, since it is working fine on the latest Mac OS and the previous versions I tested.

Would it be possible to add this?

Alternatively, if you don't want to add this, maybe you can point me in the right direction on how to set this up with my current projects without overriding the main entrypoint of the image.

Thanks.
