### ISSUE TITLE
Support for Shopware Version 6.5

### ISSUE THREAD

**Issue by h3llj0ck3y** [dockware/dockware#173]
I noticed that we are not able to set the node version to >=18. This is required for the Shopware Version 6.5.
Is there a way to change the version in the container? 
Please give me any advise if i could change this in the Dockerfile.

**Comment by h3llj0ck3y** [comment]
Now i used the dockware/6.5.0.0 docker template to start the environment. But it always exited with code 1.
I think it stucks if it wants to start the mysql server.

![image](https://github.com/dockware/dockware/assets/59047963/1162289e-2308-417c-88cb-5488424551c8)

**Comment by grosssmutttr** [comment]
In Shopware 6.5 it is also no longer possible to download the zip file from here:
https://www.shopware.com/en/changelog/

See this:
https://www.shopware.com/en/news/the-improved-shopware-installer/

So it is no longer possible to setup the essential image as described in the docs:
https://docs.dockware.io/tips-and-tricks/create-a-new-project

Additionally if defining a node_version=18 it shows the following in the docker container:
2023-05-26 18:30:32 shopware6-5  | ! WARNING: Version '18' does not exist.
2023-05-26 18:30:32 shopware6-5  | default -> 18 (-> N/A)

`version: "3"

services:
  shopware6-5:
    image: dockware/essentials:latest
    container_name: shopware6-5
    ports:
      - "80:80"
      - "3306:3306"
      - "22:22"
      - "8888:8888"
      - "9999:9999"
      - "9998:9998"
    networks:
      - web
    environment:
      - XDEBUG_ENABLED=1
      - PHP_VERSION=8.1
      - NODE_VERSION=18 #12|14|16|18

networks:
  web:
    external: false`

PHP_VERSION=8.2 also does not work as it does not find the corresponding php-fpm version.

**Comment by rmobis** [comment]
> Now i used the dockware/6.5.0.0 docker template to start the environment. But it always exited with code 1. I think it stucks if it wants to start the mysql server.
> 
> ![image](https://user-images.githubusercontent.com/59047963/240507443-1162289e-2308-417c-88cb-5488424551c8.png)

I was having the same issue (with both `6.5.0.0` and the newly released `6.5.1.0`). Removing my docker db volume "fixes" the issue, though it does not allow persisting data between invocations. `docker-compose.yml` for reference:

```
version: "3"

services:
    shopware:
        image: dockware/dev:6.5.1.0
        container_name: dockware65-dev
        ports:
            - "80:80"
            - "3306:3306"
            - "22:22"
            - "8080:8080"
            - "8888:8888"
            - "9999:9999"
            - "9998:9998"
        volumes:
            - source:/var/www/html
#            - db:/var/lib/mysql
            - C:/Users/rmobi/.ssh/id_rsa:/var/www/.ssh/id_rsa:ro
            - C:/Users/rmobi/.ssh/id_rsa.pub:/var/www/.ssh/id_rsa.pub:ro
            - C:/Users/rmobi/.ssh/known_hosts:/var/www/.ssh/known_hosts:ro
        networks:
            - web
        environment:
            - PHP_VERSION=8.1
            - NODE_VERSION=18
            - XDEBUG_ENABLED=1
volumes:
    source:
        driver: local
    db:
        driver: local

networks:
    web:
        external: false
```
