### ISSUE TITLE
psh.phar is missing

### ISSUE THREAD

**Issue by bst27** [dockware/dockware#18]
**Describe the bug**
After setting up the Shopware installation using dockware the **psh.phar** is missing.

**To Reproduce**
Use `docker-compose up -d` with the following `docker-compose.yml` taken from https://docs.shopware.com/en/shopware-platform-dev-en/system-guide/system-installation-guides/dockware:
```
version: "3"

services:

  shopware:
    # use either tag "latest" or any other version like "6.1.5", ...
    image: dockware/dev:latest
    container_name: shopware
    ports:
      - "80:80"
      - "3306:3306"
      - "22:22"
      - "8888:8888"
      - "9999:9999"
    volumes:
      - "db_volume:/var/lib/mysql"
      - "shop_volume:/var/www/html"
    networks:
      - web
    environment:
      # default = 0, recommended to be OFF for frontend devs
      - XDEBUG_ENABLED=1
      # default = latest PHP, optional = specific version
      - PHP_VERSION=7.4

volumes:
  db_volume:
    driver: local
  shop_volume:
    driver: local

networks:
  web:
    external: false
```
Jump into the docker container with `docker exec -it shopware /bin/bash` and notice `psh.phar` is missing:

```
www-data@a7e0818b5dfb:~/html$ ./psh.phar
bash: ./psh.phar: No such file or directory
```

**Expected behavior**
After jumping into the docker container I expect to receive a list of available commands after executing `./psh.phar`.
