### ISSUE TITLE
SalesChannelMappingException when starting on port other than 80

### ISSUE THREAD

**Issue by flowl** [dockware/dockware#187]
```
version: "3"

services:

  shopware:
    # use either tag "latest" or any other version like "6.5.3.0", ...
    image: dockware/dev:latest
    container_name: shopware
    ports:
      - "180:80"
      - "13306:3306"
      - "122:22"
      - "18888:8888"
      - "19999:9999"
    volumes:
      - "db_volume:/var/lib/mysql"
      - "shop_volume:/var/www/html"
    networks:
      - web
    environment:
      # default = 0, recommended to be OFF for frontend devs
      - XDEBUG_ENABLED=1
      # default = latest PHP, optional = specific version
      - PHP_VERSION=8.1

volumes:
  db_volume:
    driver: local
  shop_volume:
    driver: local

networks:
  web:
    external: false
```

> Unable to find a matching sales channel for the request: "http://localhost:180/". Please make sure the domain mapping is correct.

```
Shopware\Storefront\Framework\Routing\Exception\SalesChannelMappingException:
Unable to find a matching sales channel for the request: "http://localhost:180/". Please make sure the domain mapping is correct.

  at /var/www/html/vendor/shopware/storefront/Framework/Routing/RequestTransformer.php:113
  at Shopware\Storefront\Framework\Routing\RequestTransformer->transform()
     (/var/www/html/vendor/shopware/core/HttpKernel.php:123)
  at Shopware\Core\HttpKernel->doHandle()
     (/var/www/html/vendor/shopware/core/HttpKernel.php:65)
  at Shopware\Core\HttpKernel->handle()
     (/var/www/html/public/index.php:71)
  at Symfony\Component\HttpKernel\HttpKernelInterface@anonymous/var/www/html/public/index.php:61$0->handle()
     (/var/www/html/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php:35)
  at Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
     (/var/www/html/vendor/autoload_runtime.php:29)
  at require_once('/var/www/html/vendor/autoload_runtime.php')
     (/var/www/html/public/index.php:14)                
```

The "dockware" project is heavily buggy and outdated...
