### ISSUE TITLE
Dockware image with Exited(3)

### ISSUE THREAD

**Issue by nimo23** [dockware/dockware#192]
**Describe the bug**
I executed the following command:

`docker run --rm -p 80:80 dockware/play:latest`

but dockware exits immediately after start with `error code 3`.

I also tried to use `docker-compose.yml` with the following content:

```
version: '3'

services:
  shop:
    container_name: shop
    image: dockware/play:latest
    ports:
      - "22:22"     # ssh
      - "80:80"     # apache2
      - "443:443"   # apache2 https
      - "8888:8888" # watch admin
      - "9998:9998" # watch storefront proxy
      - "9999:9999" # watch storefront
      - "3306:3306" # mysql port
    #volumes:
    #  - "./src:/var/www/html"
    #  - "./src:/var/www/html/custom/plugins"
    networks:
      - web
    environment:
      - XDEBUG_ENABLED=1
    tty: true

## ***********************************************************************
##  NETWORKS
## ***********************************************************************
networks:
  web:
    external: false
```

and executed `docker compose up -d`, but it also exits immediately after start with `error code 3`:

![Screenshot at Sep 18 23-24-58](https://github.com/dockware/dockware/assets/3045549/c3cc7881-7f3f-45b1-8a78-5e43f744a2e6)

**To Reproduce**
1. use Docker Desktop on Mac OS
2. zsh command: `docker run --rm -p 80:80 dockware/play:latest`
3. docker container exits immediately after start with error code 3

**Expected behavior**
The container should run.

**Desktop (please complete the following information):**
 - Mac OS (Intel)

**Additional context**
Please provide at least a hint in https://docs.dockware.io FAQ to explain what `error code 3` means.
