### ISSUE TITLE
Add a recovery mode to be able to repair broken Dockware containers

### ISSUE THREAD

**Issue by SanderFlooris** [dockware/dockware#201]
**Is your feature request related to a problem? Please describe.**
It has happened multiple times where a bug can cause the container to fail during startup, and because it happens during startup, you can't resolve the issue.

This often ends up with us just having to throw away the container, including all the data that is inside.

**Describe the solution you'd like**
A sort of "recovery mode" where it doesn't start any scripts or services during startup.
This way if a service or command fails during boot, you can at least enter the container and attempt to fix it.

An environment variable would probably be a simple way to enable it.
Something like `RECOVERY_MODE=1` to enable it.

```yaml
version: "3"
services:
    shopware:
      # use either tag "latest" or any other version like "6.1.5", ... 
      image: dockware/dev:6.5.4.1
      container_name: shopware
      volumes:
         - "db_volume:/var/lib/mysql"
         - "shop_volume:/var/www/html"
      networks:
        - default
      environment:
         # Disables loading services and scripts during startup
         - RECOVERY_MODE=1 
         # default = 0, recommended to be OFF for frontend devs 
         - XDEBUG_ENABLED=1
         # default = latest PHP, optional = specific version 
         - PHP_VERSION=8.1
         # Specify the shop URL
         - SHOP_DOMAIN=shopware.localhost
volumes:
  db_volume:
    driver: local
  shop_volume:
    driver: local

```

**Describe alternatives you've considered**
Most of the time it's a matter of being really fast, and hope that you are fast enough to execute the command before the container dies.
Which of course isn't optimal, and sometimes is just straight up impossible if it dies very early.

**Additional context**
For example: Here we have a container that refuses to start, because one of the Composer dependencies is broken.
We are unable to repair this container, since it dies pretty early, while the problem itself probably isn't that hard to resolve if we were actually able to enter the container.

![Scherm­afbeelding 2023-11-28 om 15 40 24](https://github.com/dockware/dockware/assets/116890267/e06ddd0b-7d34-48dc-bd5b-5aa8bfa076dd)
