### ISSUE TITLE
HTTPS doesnt work with exposed port 443 or 80

### ISSUE THREAD

**Issue by tehseensajjad** [dockware/dockware#203]
**Describe the bug**
I'm trying to host dockware/dev for my devs to develop against their REST API.
We're using EKS in AWS. To host:
1. Deployment that creates pods that expose 443
2. Service that routes 443 to 443 on pod
3. Ingress that creates exernal loadbalancer to service port. A subdomain `example.company.com` is bound to this loadbalancer.

Visiting https://example.company.com gives the following error:

```
Bad Request

Your browser sent a request that this server could not understand.
Reason: You're speaking plain HTTP to an SSL-enabled server port.
Instead use the HTTPS scheme to access this URL, please.
```

**To Reproduce**

Deployment:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shopware
  name: shopware
  namespace: shopware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopware
  template:
    metadata:
      labels:
        app: shopware
    spec:
      containers:
      - image: dockware/dev:6.5.7.3
        imagePullPolicy: IfNotPresent
        resources: {}
        name: dev
        ports:
        - name: web-ssl
          containerPort: 443
        env:
        - name: TZ
          value: Europe/London
        - name: SHOP_DOMAIN
          value: example.company.com
        - name: XDEBUG_ENABLED
          value: "1"
        - name: PHP_VERSION
          value: "8.1"
---
apiVersion: v1
kind: Service
metadata:
  name: shopware
  namespace: shopware
spec:
  selector:
    app: shopware
  ports:
  - port: 443
    targetPort: 443
    name: web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: <REDACTED>
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  name: shopware
  namespace: shopware
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - backend:
          service:
            name: shopware
            port:
              number: 443
        path: /
        pathType: Prefix
```

**Expected behavior**
As per documentation, exposing port 443 should make HTTPS work.

**Screenshots**
![image](https://github.com/dockware/dockware/assets/100869004/e9707a06-fe47-4afb-906f-57156c0a8c6d)

**Desktop (please complete the following information):**
 - OS: Amazon Linux 2 (EKS Node OS, dont think it matters)
 - Browser: Firefox
 - Version 119.0.1
