### ISSUE TITLE
`git lfs` missing in `dockerwas/dev` 

### ISSUE THREAD

**Issue by digitalkaoz** [dockware/dockware#212]
**Describe the bug**
when working with `git lfs` its needed to have `git-lfs` installed.  one can manually install it, but when using the image in CI there is no proper to have `git-lfs` installed before the pipeline *git clones* the repository

this needs to be included in the build process:

```bash
curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
apt-get install git-lfs
``` 

**To Reproduce**
clone a repo with lfs enabled and try a `git lfs pull`

**Expected behavior**
`git clone` in CI has `git-lfs` installed and can properly clone the repo.

**Additional context**
here is an example bitbucket pipeline:

```yaml
image: php:8.1

clone:
  lfs: true # should pull the lfs files already, bit since lfs is not available we need to pull manually later

definitions:
  steps:
    - step: 
        name: "lfs test"
        image: dockware/dev:6.5.6.0
        script:
          - cd $BITBUCKET_CLONE_DIR
          - git lfs pull # manual pull fails
```
