### ISSUE TITLE
Include external Database (MYSQL)

### ISSUE THREAD

**Issue by Praktikant1981** [dockware/dockware#213]
Hi, I would like to take up this topic too. So far all attempts have failed.

https://docs.dockware.io/faq/dockware-and-other-images

It is described here that it is possible to use an “external” MYSQL server.
I don't know what I'm doing wrong but the container simply doesn't take over the data from the .env but the internal server is always used.
What can I do or what am I doing wrong?

Maybe someone has managed it and can tell you how to do it?!

Thank you in advance!

**Comment by boxblinkracer** [comment]
Hi

what do you mean by "taking over the data"? or what is still used from the internal server?

if you have a different MySQL container, then you just need to change the .env connection string to that host and then the dockware or Shopware container connects to a remote DB on another container

all database data is then on that container and not in dockware anymore

**Comment by Praktikant1981** [comment]
thanks for the quick reply.
```

version: "3"

services:

     shopware:
       image: dockware/play:latest
       container_name: shopware
       ports:
          - "80:80"
       networks:
          - web

     db:
       image: mysql:5.7
       container_name: mysql
       networks:
         - web
       environment:
         - MYSQL_ROOT_PASSWORD=hidden
         - MYSQL_USER=shopuser
         - MYSQL_PASSWORD=secret
         - MYSQL_DATABASE=shopware

networks:
   web:
     external: false
```


with the .env with the content

```
DATABASE_URL=mysql://shopuser:secret@db:3306/shopware
```
unfortunately the data is written to the "internal" database.

I've also

```
 env_file:
         - .env
```

still integrated into the docker-compose.yml. The “internal” database was also used here.

I would also be happy to post the logs here, maybe you can then say more about what the problem is?!
