### ISSUE TITLE
Missing php8.3 xdebug 

### ISSUE THREAD

**Issue by Filefabrik** [dockware/dockware#215]
https://github.com/dockware/dockware/blob/c01d908e9d0383ff44be4b87bdfa44877532bf97/.dist/versions/master/flex/latest/Dockerfile#L781

COPY ./config/php/xdebug-3.ini /etc/php/8.3/fpm/conf.d/20-xdebug.ini
COPY ./config/php/xdebug-3.ini /etc/php/8.3/cli/conf.d/20-xdebug.ini

Sed it also 8.3 currently not exists
https://github.com/dockware/dockware/blob/c01d908e9d0383ff44be4b87bdfa44877532bf97/.dist/versions/master/flex/latest/Dockerfile#L781

**Comment by patchee500** [comment]
Also happens for the Essentials Image:

```
*** | sed: can't read /etc/php/8.3/fpm/conf.d/20-xdebug.ini: No such file or directory
*** | sed: can't read /etc/php/8.3/cli/conf.d/20-xdebug.ini: No such file or directory
```

**Comment by KaiOnGitHub** [comment]
I found the following solution to use Xdebug with PHP 8.3 and dockware/dev:latest. It only works for me if I run ```sudo apt-get update``` before the [xdebug install which was btw added 1 month ago](https://github.com/dockware/dockware/blame/33385ff1f2da4efb796bcfefed4b42e6af125c24/template/components/php/8.3/install.sh.twig#L18) by @boxblinkracer.


I created a custom_entrypoint.sh:
```
#!/bin/bash
# custom_entrypoint.sh

nvm install 20

# install Xdebug
sudo apt-get update
sudo apt-get install -y php8.3-xdebug

exec /bin/bash "/entrypoint.sh"
```

loaded in the docker-compose.yml:
```
version: "3"

services:

  shopware:
    build: .
    ...
    environment:
      - PHP_VERSION=8.3
      - XDEBUG_ENABLED=1
      - NODE_VERSION=20

    volumes:
     ...
      - "./custom_entrypoint.sh:/usr/local/bin/custom_entrypoint.sh"

    entrypoint: ["/usr/local/bin/custom_entrypoint.sh"]
...
```

and used dockware:dev as base image in my Dockerfile:
```
FROM dockware/dev:latest
```
