### ISSUE TITLE
Docker volume watch-admin not working

### ISSUE THREAD

**Issue by AcrisDavidGratschmayer** [dockware/dockware#216]
**Describe the bug**
The admin watch command does not recompile after a file changes with bind mounts.

**To Reproduce**

```yaml
version: "3"
 
services:
  shopware:
    image: dockware/dev:6.5.8.6
    container_name: sw6586
    ports:
      - "80:80"
      - "3306:3306"
      - "22:22"
      - "8888:8888"
      - "9999:9999"
      - "9998:9998"
    volumes:
      - shop_volume:/var/www/html/custom
    networks:
      - web
    environment:
      - XDEBUG_ENABLED=1
 
volumes:
  shop_volume:
    driver: local
    driver_opts:
      type: 'none'
      device: '.\\src\\custom'
      o: 'bind'
 
networks:
  web:
    external: false
```

**Expected behavior**
It should recompile after a file changes

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 6.5.*, 6.6.* (maybe on ever image)

**Comment by gychem** [comment]
I have the same issue, did you manage to find a solution?

**Comment by AcrisDavidGratschmayer** [comment]
Not yet. I'm still using the non bind mode. The only thing i persistet is the database (docker internally). Because for some reason you cannot mount it (will crash container). `shop_volume` is commented.

```yml
version: "3"

services:
  shopware:
    image: dockware/dev:6.6.0.2
    container_name: sw6602
    ports:
      - "80:80"
      - "3306:3306"
      - "22:22"
      - "8888:8888"
      - "9999:9999"
      - "9998:9998"
    volumes:
      - db_volume:/var/lib/mysql
    #   - shop_volume:/var/www/html/custom
    networks:
      - web
    environment:
      - XDEBUG_ENABLED=1

volumes:
  shop_volume:
    driver: local
    driver_opts:
      type: 'none'
      device: '.\\src\\custom'
      o: 'bind'
  db_volume:
    driver: local

networks:
  web:
    external: false
```
