### ISSUE TITLE
Can not run bin/build-administration.sh because of unmet dependencies vue@"2.7.14"

### ISSUE THREAD

**Issue by thomasdcodes** [dockware/dockware#222]
I started a new dockware/dev:6.5.8.10 container, connected via docker exec and tried to build the administration:
```
services:

  shopware:
    image: dockware/dev:6.5.8.10
    container_name: shopware6_kunde
    ports:
      - "80:80"
      - "3306:3306"
      - "22:22"
      - "8888:8888"
      - "9999:9999"
      - "9998:9998"
    networks:
      - web
    environment:
      - PHP_VERSION=8.2
      - NODE_VERSION=18
      - XDEBUG_ENABLED=0

networks:
  web:
    external: false
```

I got this error:

```
npm WARN config production Use `--omit=dev` instead.
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @vue/server-renderer@3.3.4
npm WARN Found: vue@3.3.4
npm WARN node_modules/vue3/node_modules/vue
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer overridden vue@"2.7.14" (was "3.3.4") from @vue/server-renderer@3.3.4
npm WARN node_modules/vue3/node_modules/@vue/server-renderer
npm WARN   @vue/server-renderer@"3.3.4" from vue3@3.3.4
npm WARN   node_modules/vue3
npm WARN   1 more (vue)

> administration@1.0.0 preinstall
> node src/scripts/validate-package-json/index.mjs


> administration@1.0.0 postinstall
> patch-package

sh: 1: patch-package: not found
npm ERR! code 127
npm ERR! path /var/www/html/vendor/shopware/administration/Resources/app/administration
npm ERR! command failed
npm ERR! command sh -c patch-package

```

I'm not sure if this is a Shopware issue or it has something to do with this dockware container.
