### ISSUE TITLE
Creates everything as root user

### ISSUE THREAD

**Issue by 0zd0** [dockware/dockware#223]
**Describe the bug**
My host user is not root. When the default docker-compose.yml is launched, then when mounting `- ./shopware:/var/www/html` everything is done internally from the root user. If you change the owner through sh scripts or Dockerfile, then some kind of build error with rights will definitely occur

**To Reproduce**
```yml
services:
  shopware:
    image: dockware/dev:6.6.4.0
    container_name: ${APP_NAME}-shopware
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:80"
      - "${DB_PORT}:3306"
      - "${SSH_PORT}:22"
    environment:
      - XDEBUG_ENABLED=1
      - SHOP_DOMAIN=shopware.local
    volumes:
      - tokenpay_shopware_db:/var/lib/mysql
      - shop_volume:/var/www/html
      - "./boot_start.sh:/var/www/boot_start.sh"
      - ./shopware:/var/www/html
    networks:
      - shopware-network
#    user: "7788:33"

volumes:
  tokenpay_shopware_db:
    driver: local
  shop_volume:
    driver: local

networks:
  shopware-network:
```

**Expected behavior**
I can mount the site folder and have access to these files

**Desktop:**
 - OS: Arch Linux
