### ISSUE TITLE
Shopware always send shopUrl as http instead https during app registration

### ISSUE THREAD

**Issue by maciejregula** [dockware/dockware#224]
I run my shopware dockware image with ssl enabled. I expose port 443, and removed port 80.
Below is my compse.yml config:

```
services:
  shopware:
    image: dockware/dev:6.5.8.2 # use either tag "latest" or any other version like "6.5.3.0"
    container_name: shopware-6.5.8.2
    ports:
      - "3306:3306"
      - "22:22"
      - "8888:8888"
      - "9999:9999"
      - "443:443"
    volumes:
      - "mysql_shopware-6.5.8.2_data:/var/lib/mysql"
      - "shopware-6.5.8.2_data:/var/www/html"
      - "./src/shopware-app/custom/apps/OrbitvuSun:/var/www/html/custom/apps/OrbitvuSun"
      - "./certs/shop/server.crt:/etc/apache2/ssl/server.crt"
      - "./certs/shop/server.key:/etc/apache2/ssl/server.key"
    environment:
      - XDEBUG_ENABLED=0 # default = 0, recommended to be OFF for frontend devs
      - PHP_VERSION=8.1 # default = latest PHP, optional = specific version
      - SHOP_DOMAIN=shopware-6582.docker
```

When I install my app in the Shopware shop back office I always receive "shop-url=**http://**shopware-6582.docker" query param with **http://** instead of **https://**. I enter Shopware backoffice via https. Shopware backoffice without SSL is disabled. So why Shopware always send http as shop URL instead https ?

The main problem is that when I reach Shopware SHOP API via my custom application code and in app database shop URL is : **http://**shopware-6582.docker and for example I request the shop API for product images I also receive from the API, URL of the images without "https".
