### ISSUE TITLE
ZSTD PHP Extension

### ISSUE THREAD

**Issue by Catalin-Ionut** [dockware/dockware#237]
**Shopware 6 Performance**
Since Shopware 6.6.4.0, it has been possible to use zstd as an alternative compression algorithm. zstd is faster than gzip and has a better compression ratio.

```
# Enabling cart compression with zstd
shopware:
    cart:
      compress: true
      compression_method: zstd
```

```
# Enabling cache compression with zstd
shopware:
  cache:
    cache_compression: true
    cache_compression_method: 'zstd'
```
**To Reproduce**

1. Enable the above configuration
2. Go on any page
3. See error regarding zstd method not allowed / installed.

**Expected behavior**
Shop should work out of the box with this configuration since this is a shopware standard feature we can use and test.
