### ISSUE TITLE
latest tag not working in mac

### ISSUE THREAD

**Issue by kooliahmd** [dockware/dockware#244]
**Describe the bug**
docker-compose up fails on mac

**To Reproduce**
Using below `docker-compose.yml` content taken from the official doc of shopware
```
services:

    shopware:
      # use either tag "latest" or any other version like "6.5.3.0", ...
      image: dockware/dev:latest
      container_name: shopware
      ports:
         - "80:80"
         - "3306:3306"
         - "22:22"
         - "8888:8888"
         - "9999:9999"
      volumes:
         - "db_volume:/var/lib/mysql"
         - "shop_volume:/var/www/html"
      networks:
         - web
      environment:
         # default = 0, recommended to be OFF for frontend devs
         - XDEBUG_ENABLED=1
         # default = latest PHP, optional = specific version
         - PHP_VERSION=8.1

volumes:
  db_volume:
    driver: local
  shop_volume:
    driver: local

networks:
  web:
    external: false

```
I get this error:
```
 _____   ____   _____ _  ____          __     _____  ______
|  __ \ / __ \ / ____| |/ /\ \        / /\   |  __ \|  ____|
| |  | | |  | | |    | ' /  \ \  /\  / /  \  | |__) | |__
| |  | | |  | | |    |  <    \ \/  \/ / /\ \ |  _  /|  __|
| |__| | |__| | |____| . \    \  /\  / ____ \| | \ \| |____
|_____/ \____/ \_____|_|\_\    \/  \/_/    \_\_|  \_\______|

68 69 20 64 65 76 65 6C 6F 70 65 72 2C 20 6E 69 63 65 20 74 6F 20 6D 65 65 74 20 79 6F 75
6c 6f 6f 6b 69 6e 67 20 66 6f 72 20 61 20 6a 6f 62 3f 20 77 72 69 74 65 20 75 73 20 61 74 20 6a 6f 62 73 40 64 61 73 69 73 74 77 65 62 2e 64 65

*******************************************************
** DOCKWARE IMAGE: dev
** Tag: 6.6.9.0
** Version: 1.8.0
** Built: Fri Nov 29 21:51:33 UTC 2024
** Copyright 2022 dasistweb GmbH
*******************************************************

launching dockware...please wait...

DOCKWARE: setting timezone to Europe/Berlin...

Current default time zone: 'Europe/Berlin'
Local time is now:      Wed Dec 18 21:06:43 CET 2024.
Universal Time is now:  Wed Dec 18 20:06:43 UTC 2024.

-----------------------------------------------------------
DOCKWARE: restarting SSH service....
 * Restarting OpenBSD Secure Shell server sshd
   ...done.
-----------------------------------------------------------
DOCKWARE: starting MySQL....
 * Starting MySQL database server mysqld
   ...done.
-----------------------------------------------------------
DOCKWARE: starting mailcatcher....
Starting MailCatcher v0.9.0
==> smtp://0.0.0.0:1025
==> http://0.0.0.0:1080
*** MailCatcher runs as a daemon by default. Go to the web interface to quit.
-----------------------------------------------------------
DOCKWARE: starting cron service....
 * Starting periodic command scheduler cron
   ...done.
-----------------------------------------------------------
DOCKWARE: switching to PHP 8.1...
sudo service php8.1-fpm start
php8.1-fpm: unrecognized service
make: *** [makefile:50: switch-php] Error 1
```

**Expected behavior**
Docker container up

**Desktop (please complete the following information):**
 - OS: Sequoia 15.2
 - Chip: Apple M3 Pro
