### ISSUE TITLE
Product creation fails for shops with MYSQL_USER and MYSQL_PWD set

### ISSUE THREAD

**Issue by macster84** [dockware/dockware#26]
### Happy Christmas bug report!

**Describe the bug**
Product creation fails via new product page or import when MYSQL_USER and MYSQL_PWD are set.
The error is:
`SQLSTATE[HY000]: General error: 1449 The user specified as a definer ('root'@'%') does not exist`

This seems to be related to [this line](https://github.com/dockware/dockware/blob/144ae12445cdbc3c72ed22a678ac432bc382f561/template/entrypoint.global.sh.twig#L118) where root access is restricted to localhost once a MYSQL_USER is set.
Unfortunately Shopware defines database triggers that still reference '_root@%_' as definer:

- product_purchase_prices_insert
- product_purchase_prices_update
- product_listing_price_update

 This can be easily seen when running '_show triggers_' via mysql shell.

I eventually changed the definer manually to 'root@localhost' for all triggers like outlined [here](https://stackoverflow.com/a/18596425).
Afterwards product creation does not yield a 500 error anymore. Also import worked like a charm.

**To Reproduce**
Start dockware/dev with a MYSQL_USER and MYSQL_PWD.
```
version: "3.8"

services:
    shopware:
        image: dockware/dev:6.3.4.0
        container_name: shopware
        networks:
            - web
        environment:
            - XDEBUG_ENABLED=0
            - MYSQL_USER=app
            - MYSQL_PWD=app

networks:
    web:
        external: false
```

Afterwards try to create  a product either by the new product page or by import.

**Expected behavior**
Product creation succeeds without errors.

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: Chrome
