### ISSUE TITLE
Dockefile

### ISSUE THREAD

**Issue by Carsten750** [dockware/dockware#37]
Hello everyone

I find Dockware a super interesting project! Extremely cool!

For me it serves as a source of knowledge to learn and deepen the handling of Docker based configurations.

I'm not that familiar with Twig and Orca, unfortunately. How do you create a Dockerfile from the twigs? Is it possible to send me a rendered Dockerfile?

Just to give me food for some thoughts. ;-)

I would be interested in the following configuration:

```
version: "3"

services:
        
    shopware:
      image: dockware/play:latest
      container_name: shopware
      ports:
         - "80:80"
      networks:
         - web
      
    db:
      image: mysql:5.7
      container_name: mysql
      networks:
        - web
      environment:
        - MYSQL_ROOT_PASSWORD=hidden
        - MYSQL_USER=shopuser
        - MYSQL_PASSWORD=secret
        - MYSQL_DATABASE=shopware

networks:
  web:
    external: false
```

I would be happy if this could be done....

Carsten
