### ISSUE TITLE
Dockware inside kubernetes results in an 500 Internal Server Error

### ISSUE THREAD

**Issue by maxnowack** [dockware/dockware#38]
I'm trying to run Dockware inside a Kubernetes Cluster (setup with [k3s.io](https://k3s.io)). Not for production use, but for a development environment with a shared database.

For my initial test, I'm using a minimal config to keep it as simple as possible:
````yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopware-development
  labels:
    app: shopware-development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopware-development
  template:
    metadata:
      labels:
        app: shopware-development
    spec:
      containers:
      - name: shopware-development
        image: dockware/play
        env:
        - name: APP_ENV
          value: dev
````

If I start the deployment, start port forwarding using `kubectl port-forward <pod name> 8080:80` and open http//localhost:8080 in my browser, I'm getting the following message:
> ![Oops! An Error Occurred The server returned a "500 Internal Server Error". Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.](https://user-images.githubusercontent.com/186073/106026135-b9648e00-60c9-11eb-92e7-83aee105cf77.png)

I've checked the container logs, the php logs (`/var/log/php*`), the apache2 logs (`/var/log/apache2*`) and the shopware logs (`~/html/var/log/*`) inside the container, but there is no information what is causing the internal server error.
Did I forget to check a specific location for logs?

If I run dockware on my local docker environment, everything works fine. So it's seem that's an issue with the combination of kubernetes and dockware.

Does anyone has a clue what is happening here?
