### ISSUE TITLE
bin/console not working on a fresh `dockware/dev:latest`

### ISSUE THREAD

**Issue by owzim** [dockware/dockware#52]
**Describe the bug**
I used an example compose file from the docs

**To Reproduce**
create a docker-compose.yml

```yml
version: "3"

services:

  shopware:
    image: dockware/dev:latest
    container_name: shopware
    ports:
      - "80:80"
      - "3306:3306"
      - "22:22"
      - "8888:8888"
      - "9999:9999"
    networks:
      - web
    environment: # https://docs.dockware.io/development/environment-variables
      - XDEBUG_ENABLED=1

networks:
  web:
    external: false
```

Then I run 

```sh
docker-compose up -d --force-recreate
```

The site is working alright, frontend, backend, everything.

But when I run:

```sh
docker-compose run shopware bash -c 'bin/console'
```

I get this:

```
In AbstractMySQLDriver.php line 93:             
  An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory  
                                                                                     
In PDOConnection.php line 31:
  SQLSTATE[HY000] [2002] No such file or directory  
                                                    
In PDOConnection.php line 27:
  SQLSTATE[HY000] [2002] No such file or directory  
```

**Additional context**
OS: **macOS 10.14.6**
**Docker Engine v20.10.5**
