### ISSUE TITLE
Allow installation with different default language than english

### ISSUE THREAD

**Issue by JonasHaas** [dockware/dockware#55]
can we have a config to set the default language, without editing the db manually after the installation?

**Comment by boxblinkracer** [comment]
hi

good idea, 
would that be something like the default currency i guess? 

https://docs.dockware.io/development/environment-variables

**Comment by seybsen** [comment]
It could be a new script like [set_currency.php](https://github.com/seybsen/dockware/blob/master/template/assets/assets/shopware6/files/set_currency.php.twig) which also gets executed in [entrypoint.sh](https://github.com/dockware/dockware/blob/master/.dist/versions/master/play/6.4.10.1/entrypoint.sh#L76) and runs following statements (e.g. EN -> DE):

```
UPDATE language SET id = UNHEX(REPLACE(UUID(), '-','')) WHERE name='English';

UPDATE language SET id = UNHEX('2FBB5FE2E29A4D70AA5854CE7CE3E20B') WHERE name='Deutsch';

UPDATE user SET locale_id = (SELECT id FROM locale WHERE code = 'de-DE') WHERE username = 'admin';

UPDATE sales_channel_domain
SET language_id = (SELECT id FROM language WHERE name = 'Deutsch'),
currency_id = (SELECT id FROM currency WHERE iso_code = 'EUR'),
snippet_set_id = (SELECT id FROM snippet_set WHERE iso = 'de-DE');

UPDATE sales_channel SET language_id = (SELECT id FROM language WHERE name = 'Deutsch'),
currency_id = (SELECT id FROM currency WHERE iso_code = 'EUR'),
country_id = (SELECT id FROM country WHERE iso3 = 'DEU');
```

**Comment by boxblinkracer** [comment]
thank for this script
looks amazing
i've marked it to be started on boostday :)

**Comment by wirduzen-felix** [comment]
I'll have a look at this issue

**Comment by dg-arboro** [comment]
Any updates on this? Would really like to change the default language upon installation without doing it manually.

**Comment by axe1987** [comment]
I solved it by running this after the dockware has finished

`bin/console system:install --drop-database --basic-setup --shop-locale=de-De --create-database --skip-jwt-keys-generation --force`

But maybe it is possible to add those arguments to the docker compose file.
And then use the at this line: https://github.com/dockware/dockware/blob/47c0d3eccf256d9a964c04c77c0d509b673568cd/.dist/versions/master/dev/6.4.17.2/Dockerfile#L824

Maybe even add the remaining options for the system-install command. Maybe like:

```
    ports:
      - "22:22"     # ssh
      - "80:80"     # apache2
      - "443:443"   # apache2 https
      - "8888:8888" # watch admin
      - "9998:9998" # watch storefront proxy
      - "9999:9999" # watch storefront
      - "3306:3306" # mysql port
    networks:
      - web
    environment:
      - XDEBUG_ENABLED=0
      - SSH_USER=app
      - SSH_PWD=app
      - SW_SHOP_LOCALE=de-De
      - SW_SHOP_EMAIL=example@example.com
      - SW_NAME=myShopName
      - SW_....
     
```
