### ISSUE TITLE
Missing full featured example

### ISSUE THREAD

**Issue by btxtiger** [dockware/dockware#63]
**Is your feature request related to a problem? Please describe.**
This project seems to be great. But I am really missing a full featured example config. It is really hard to find each tiny snippet everywhere.

**Describe the solution you'd like**
Full featured example

**Additional context**
This is my docker-compose file. I can't get it running because I haven't found yet, how to advise `dockware/play` to use a different database port (I guess). Of course I am not using the default ports 80, 3306 aso. These are important ports that are either already allocated, oder have to stay free for other tools.
The default shopware setup has .env variables like `APP_ENV`, `APP_SECRET`, `APP_URL`, ... . How can I adjust them?

**Comment by btxtiger** [comment]
After a lot trial and error, I came to this setup. Feel free to include this in the docs. I'm sure it will help a lot of more developers. Would be also helpful if the unclear points could be clarified (`APP_SECRET`, `INSTANCE_ID`, `SHOPWARE_ES_INDEX_PREFIX`).

### Local .env
```
# APP_ENV=development
APP_ENV=prod
APP_SECRET=1 # what is this?
INSTANCE_ID=1 # what is this?

APP_URL=https://allaoui.shop
TRUSTED_PROXIES=REMOTE_ADDR # https://forum.shopware.com/discussion/62801/shopware-6-mit-ssl-hinter-reverse-proxy#Comment_259420

DATABASE_URL=mysql://root:root@localhost:3306/shopware
# MAILER_URL=smtp://localhost:1025
COMPOSER_HOME=/var/www/html/var/cache/composer
SHOPWARE_HTTP_CACHE_ENABLED=1

# REDIS_SESSION_HOST=redis
# REDIS_SESSION_PORT=6379
# REDIS_CACHE_HOST=redis
# REDIS_CACHE_PORT=6379

# SHOPWARE_ES_ENABLED=0
# SHOPWARE_ES_HOSTS=elasticsearch:9200
# SHOPWARE_ES_INDEXING_ENABLED=0
# SHOPWARE_ES_INDEX_PREFIX=abc # what is this?

DOCKER_MYSQL_INIT_ROOT_PASSWORD=your_db_root_password
DOCKER_MYSQL_INIT_ROOT_HOST=172.%.%.%
DOCKER_MYSQL_INIT_HOST=172.%.%.%
DB_DATABASE=shopware_docker
DB_USERNAME=docker
DB_PASSWORD=your_db_user_password
```


### Local docker-compose.yml
```yml
version: "3"

services:
        
    shopware:
      image: dockware/play:latest
      container_name: shopware_app
      environment:
        PHP_VERSION: 8.0
      volumes:
        - "shop_volume:/var/www/html"
        - ./.env:/var/www/html/.env
      ports:
         - "8766:80"
      networks:
         - web

    db:
        image: mysql:5.7
        container_name: shopware_db
        networks:
            - web
        command:
            - '--default-authentication-plugin=mysql_native_password'
            - '--character-set-server=utf8mb4'
            - '--collation-server=utf8mb4_unicode_ci'
            - '--skip-name-resolve'
        volumes:
            - db_volume:/var/lib/mysql/:cached
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'false'
            ### Database initialization config:
            MYSQL_ROOT_HOST: ${DOCKER_MYSQL_INIT_ROOT_HOST}
            MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_INIT_ROOT_PASSWORD}
            MYSQL_HOST: ${DOCKER_MYSQL_INIT_HOST}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        # ports:
        #     - 3305:3306 # Access from outside not necessary
        restart: always

    # redis:
    #     image: redis:5.0.6
    #     container_name: shopware_redis
    #     networks:
    #         - web
    
    # elasticsearch:
    #     container_name: shopware_elasticsearch
    #     image: elastic/elasticsearch:7.1.1
    #     environment:
    #         - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    #         - discovery.type=single-node

volumes:
    db_volume:
        driver: local
    shop_volume:
        driver: local


networks:
  web:
    external: false
```

**Comment by btxtiger** [comment]
After a lot trial and error, I came to this setup. Feel free to include this in the docs. I'm sure it will help a lot of more developers. Would be also helpful if the unclear points could be clarified (`APP_SECRET`, `INSTANCE_ID`, `SHOPWARE_ES_INDEX_PREFIX`).

### Local .env
```
# APP_ENV=development
APP_ENV=prod
APP_SECRET=1 # what is this?
INSTANCE_ID=1 # what is this?

APP_URL=https://myshop.com
TRUSTED_PROXIES=REMOTE_ADDR # https://forum.shopware.com/discussion/62801/shopware-6-mit-ssl-hinter-reverse-proxy#Comment_259420

DATABASE_URL=mysql://root:root@localhost:3306/shopware
# MAILER_URL=smtp://localhost:1025
COMPOSER_HOME=/var/www/html/var/cache/composer
SHOPWARE_HTTP_CACHE_ENABLED=1

# REDIS_SESSION_HOST=redis
# REDIS_SESSION_PORT=6379
# REDIS_CACHE_HOST=redis
# REDIS_CACHE_PORT=6379

# SHOPWARE_ES_ENABLED=0
# SHOPWARE_ES_HOSTS=elasticsearch:9200
# SHOPWARE_ES_INDEXING_ENABLED=0
# SHOPWARE_ES_INDEX_PREFIX=abc # what is this?

DOCKER_MYSQL_INIT_ROOT_PASSWORD=your_db_root_password
DOCKER_MYSQL_INIT_ROOT_HOST=172.%.%.%
DOCKER_MYSQL_INIT_HOST=172.%.%.%
DB_DATABASE=shopware_docker
DB_USERNAME=docker
DB_PASSWORD=your_db_user_password
```


### Local docker-compose.yml
```yml
version: "3"

services:
        
    shopware:
      image: dockware/play:latest
      container_name: shopware_app
      environment:
        PHP_VERSION: 8.0
      volumes:
        - "shop_volume:/var/www/html"
        - ./.env:/var/www/html/.env
      ports:
         - "8766:80"
      networks:
         - web

    db:
        image: mysql:5.7
        container_name: shopware_db
        networks:
            - web
        command:
            - '--default-authentication-plugin=mysql_native_password'
            - '--character-set-server=utf8mb4'
            - '--collation-server=utf8mb4_unicode_ci'
            - '--skip-name-resolve'
        volumes:
            - db_volume:/var/lib/mysql/:cached
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'false'
            ### Database initialization config:
            MYSQL_ROOT_HOST: ${DOCKER_MYSQL_INIT_ROOT_HOST}
            MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_INIT_ROOT_PASSWORD}
            MYSQL_HOST: ${DOCKER_MYSQL_INIT_HOST}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        # ports:
        #     - 3305:3306 # Access from outside not necessary
        restart: always

    # redis:
    #     image: redis:5.0.6
    #     container_name: shopware_redis
    #     networks:
    #         - web
    
    # elasticsearch:
    #     container_name: shopware_elasticsearch
    #     image: elastic/elasticsearch:7.1.1
    #     environment:
    #         - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    #         - discovery.type=single-node

volumes:
    db_volume:
        driver: local
    shop_volume:
        driver: local


networks:
  web:
    external: false
```
