### ISSUE TITLE
make watch-storefront - Permision denied

### ISSUE THREAD

**Issue by w3work** [dockware/dockware#64]
Hello,

i have some trouble to get the make watch-storefront running.

In PhpStorm i get the following error:
```
www-data@708130a66e1c:~$ make watch-storefront
cd /var/www/html && ./bin/build-storefront.sh
/bin/sh: 1: ./bin/build-storefront.sh: Permission denied
makefile:18: recipe for target 'watch-storefront' failed
make: *** [watch-storefront] Error 126
```

my docker-compose.yml file looks as follows:
```
version: "3"

services:
        
    shopware:
      image: dockware/dev:6.4.1.1
      container_name: sw6demo-w3work
      ports:
         - "80:80"
         - "3306:3306"
         - "22:22"
         - "8888:8888"
         - "9998:9998"
         - "9999:9999"
      volumes:
         - "db_volume:/var/lib/mysql"
         - "shop_volume:/var/www/html"
      networks:
         - web
      environment:
         - XDEBUG_ENABLED=1

volumes:
  db_volume:
    driver: local
  shop_volume:
    driver: local
    
networks:
  web:
    external: false
```

What could be the problem here?
