### ISSUE TITLE
Debugging Live Lock – page stick on looding on Windows with VSCode + Xdebug 3.0.3

### ISSUE THREAD

**Issue by seriewe** [dockware/dockware#79]
**Describe the bug**
Since updating to the latest Dockware version, I'm having problems getting debugging to work. 

**To Reproduce**
1. compose up a latest dockware.io container with  XDEBUG_ENABLED=1
2. connect vscode to container with the "Remote - Containers" Plugin 
3. Install Remote - Containers inside container vscode instance and create launch.json
4. start debugger
5. start chrome debugger

IDE Key is correct 
xdebug.client_host also as expected

**Expected behavior**
Page runs and I can hit breakpoints as it worked with Xdebug 2.x.

**Screenshots**
![image](https://user-images.githubusercontent.com/10572013/132105410-c2eddea3-c24f-4be2-b8e3-c0089a53601d.png)

![image](https://user-images.githubusercontent.com/10572013/132105422-8072c859-8332-49c9-9a36-3e8dc42ead18.png)

![xdebug-3-issue-vscode](https://user-images.githubusercontent.com/10572013/132105684-c3dd58d9-fa99-4bbe-bac1-12c70bbd86dc.gif)

my docker-compose.yml
```
version: "3"

services:
    shopware:
      image: dockware/dev:6.4.3.1
      container_name: mluxka
      ports:
         - "80:80"
         - "3306:3306"
         - "22:22"
         - "443:443"
         - "8888:8888"
         - "9999:9999"
         - "9998:9998"
      networks:
         - web
      environment:
         - XDEBUG_ENABLED=1

volumes:
  db_volume:
    driver: local
  shop_volume:
    driver: local

networks:
  web:
    external: false
```

**Additional context**
Is it possible to provide a config to set the port and also the start_with_request because it is recomendet as setting by Felix Becker here: https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-debug 

For Xdebug v3.x.x:
xdebug.mode = debug
xdebug.start_with_request = yes
