### ISSUE TITLE
make watch-storefront: Error 'command not found'

### ISSUE THREAD

**Issue by FynnZW** [dockware/dockware#88]
**Describe the bug**
Running `make watch-storefront` produces an error:
``` 
www-data@02f1d980861e:~$ make watch-storefront
cd /var/www/html && sudo ./bin/build-storefront.sh
sudo: ./bin/build-storefront.sh: command not found
```
It worked earlier today, strangely.
I updated Shopware via the admin backend, could that be the reason? 

**Additional context**
docker-compose.yaml
```
version: "3"

services:
  shopware:
    # use either tag "latest" or any other version like "6.1.5", ...
    image: dockware/dev:6.4.3.1-m1-test
    container_name: shopware
    ports:
      - "80:80"
      - "3306:3306"
      - "22:22"
      - "8888:8888"
      - "9998:9998"
      - "9999:9999"
    volumes:
      - "db_volume:/var/lib/mysql"
      # - "shop_volume:/var/www/html"
      - "./html:/var/www/html"
    networks:
      - web
    environment:
      # default = 0, recommended to be OFF for frontend devs
      - XDEBUG_ENABLED=0
      # default = latest PHP, optional = specific version
      - PHP_VERSION=7.4

volumes:
  db_volume:
    driver: local

networks:
  web:
    external: false
```
