### ISSUE TITLE
watch-admin not working in dockware/contribute image

### ISSUE THREAD

**Issue by jniclas** [dockware/dockware#9]
If I try to run 
```make watch-admin```
I get
```
BaseUrl for proxy is set to "undefined"

 ⚠️  You need to add the "APP_URL" as an environment variable for compiling the code. ⚠️

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! administration@1.0.0 dev: `mode=development webpack-dev-server "http://0.0.0.0"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the administration@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/www/.npm/_logs/2020-08-11T07_30_19_654Z-debug.log
makefile:19: recipe for target 'watch-admin' failed
make: *** [watch-admin] Error 1
```
Container runs with docker-compose:
```
sw:
        image: dockware/contribute
        container_name: sw
        ports:
            - "80:80"
            - "22:22"
            # Admin Watcher Port
            - "8888:8888"
            # Storefront Watcher Port
            - "9999:9999"
        environment:
            - PHP_VERSION=7.4
            - XDEBUG_ENABLED=1
            - SW_CURRENCY=EUR
            - PHP_IDE_CONFIG=serverName=PHPStorm
```
Same thing works great with ```dockware/dev:6.1.5```
