### ISSUE TITLE
Split the services in separate container

### ISSUE THREAD

**Issue by azngeek** [dockware/dockware#94]
**Is your feature request related to a problem? Please describe.**

I like the basic idea behind dockware as it brings most of the tools which are required for developing stuff. However the fact that there is only a single container which is treaded like a virtual machine makes this image really unflexible. Any existing service like nginx, mysql, redis, etc. could easily be added as individual container.

**Describe the solution you'd like**

- The basic Dockerfile could be used as it is. In fact, there will be an additional Dockerfile for more advanced setups.
- For advanced setups there will be a docker-compose.yaml as default with preconfigured services
- Reduce number of layers in the docker files and decrease maintenance for external services. 

**Additional context**

This is an example how this approach could be used in a working environment. 

Note: We would be happy to contribute.

```
version: "3"

services:
  php:
    image: dockware/dev:6.4.6.1
    container_name: ${PROJECT_NAME}_php
    depends_on:
      - mysql
      - elasticsearch
      - mailhog
    environment:
      - PHP_SERVERNAME=${PROJECT_TLD}
      - PHP_IDE_CONFIG=serverName=${PROJECT_TLD}
      - PHP_DEBUGGER=${PHP_DEBUGGER}
      - XDEBUG_REMOTE_HOST=${HOST_IP}
      - MYSQL_USER=super
      - MYSQL_PASSWORD=super123
      - REMOTE_DB=${REMOTE_MYSQL_DB}
      - FOS_TOKEN=${FOS_TOKEN}
    volumes:
      - ${SSH_KEY_FILE}:/root/.ssh/id_rsa:ro
      - ${DOCKER_VOLUME}/www:/var/www/share/dev/htdocs:delegated
    networks:
      ms_web: { aliases: [ "link_php" ] }

  web:
    container_name: ${PROJECT_NAME}_web
    build: ${DOCKER_REPOSITORY}/shopware/builds/web
    volumes:
      - ${DOCKER_VOLUME}/www:/var/www/share/dev/htdocs:delegated
    networks:
      ms_web: { aliases: [ "link_web", "link_fpc" ] }
    depends_on:
      - php

  ssl:
    container_name: ${PROJECT_NAME}_ssl
    build:
      context: ${DOCKER_REPOSITORY}/shopware/builds/ssl
      args:
        cn: shopware.test
        alt_names: us.shopware.test uk.shopware.test
    networks:
      ms_web: { aliases: [ "link_ssl" ] }
    ports:
      - 80:80
      - 443:443
      - 7000:7000
    depends_on:
      - web

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: ${PROJECT_NAME}_elastic
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=false
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      ms_web: { aliases: [ "link_elastic" ] }

  mysql:
    container_name: ${PROJECT_NAME}_mysql
    build: ${DOCKER_REPOSITORY}/shopware/builds/mysql
    environment:
      - MYSQL_USER=sqluser
      - MYSQL_PASSWORD=anypassword
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ms_data:/var/lib/mysql
    networks:
      ms_web: { aliases: [ "link_mysql" ] }
    ports:
      - 3307:3306
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE, fixes 'mbind: Operation not permitted' in error log
    sysctls:
      net.core.somaxconn: 518

  mailhog:
    image: mailhog/mailhog
    container_name: ${PROJECT_NAME}_mail
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      ms_web: { aliases: [ "link_mailhog" ] }

networks:
  ms_web:
    driver: bridge

volumes:
  ms_data:

```
