### ISSUE TITLE
MariaDB preinstalled?

### ISSUE THREAD

**Issue by boxblinkracer** [dockware/dockware#96]
We might want to think about a MariaDB installation somehow?
But I'm not quite sure if its better to have separate tags? or installed next to MySQL?

**Comment by roman-1983** [comment]
Why not have mysql as separate service instead of having it inside the shopware-app-container?

**Comment by martinweinmayr** [comment]
main cause is "ease of use" it is super easy to use dockware, as well as possible to launch seperate service containers with it. 
As we are deliver a installed database with some data. 

Currently we think about to store the db dump of each image in the web, that you could fire a make command to get the database dump imported to the container of your choice.

**Comment by Nico-Schaefer-2111** [comment]
would be nice to decide if dockware should use mysql or mariadb with an environment variable.

**Comment by carstenjaksch** [comment]
We want to migrate from Devenv to Dockware because of some critical issues (basically does not work anymore).

But we use MariaDB. I found [this image tag](https://hub.docker.com/layers/dockware/essentials/maria-db/images/sha256:9137bfd2ce3e1620e1079217c9cebd9034ea2568fd72dea3deb0ed0493e63b2f), but it is 3 years old. Any chance it could get some love and updates?

**Comment by Nico-Schaefer-2111** [comment]
Hey @carstenjaksch we implemented "external" databases within the docker-compose.yml, where we can switch between mariadb and mysql 8 very comfortably, plus you have an autonome container for the database :)

**Comment by carstenjaksch** [comment]
@Nico-Schaefer-2111 Thank you! Could you provide an example `docker-compose.yml` with a separate MariaDB container?

This is what I got from the docs:

```
services:
  shopware:
    image: dockware/essentials:latest
    container_name: shopware
    ports:
      - "80:80"
      - "443:443"
      - "3306:3306"
      - "22:22"
      - "8888:8888"
      - "9999:9999"
      - "9998:9998"
    networks:
      - web
    environment:
      - XDEBUG_ENABLED=1
networks:
  web:
    external: false
```
